import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Blocks, Bot, Code2, Gauge, Globe2, LayoutTemplate, LifeBuoy, Rocket, ShieldCheck, Smartphone, Workflow } from 'lucide-react'
import { LanguageRedirect } from './LanguageRedirect'
import { LanguageSwitch } from './LanguageSwitch'
import { ProjectDetails } from './ProjectDetails'

const project = {
 en:{title:'You have the idea. I build the project.',lead:'Apps, web apps, internal tools, automations and MVPs — from the first structure to a finished, usable product.',badge:'Product development with Vantura',services:[['Apps & web apps','Responsive products for mobile and web, built for real usage.',Smartphone],['MVPs & prototypes','Turn an idea into a testable first version without months of preparation.',Blocks],['Automation','Workflows, integrations and AI processes that reduce manual work.',Workflow],['Internal tools','Dashboards, calculators and portals tailored to your operation.',Gauge],['Project rescue','Analyse, stabilise and finish incomplete or stalled projects.',LifeBuoy],['AI features','Integrate useful AI features, agents and local models into products.',Bot]],process:'Clear process. Early results.',steps:[['01','Understand','We clarify the goal, users and what the first useful version must do.'],['02','Plan & prototype','You receive a clear scope, user flow, technical direction and an early concept.'],['03','Design & build','I develop in short iterations and show working results early.'],['04','Launch & support','Deployment, setup, handover and optional ongoing support.']],cta:'Tell me what your project should do.',button:'Discuss your idea',selected:'Selected projects',selectedLead:'A mix of live products, internal systems and focused experiments.',cross:'Need a strong public-facing presence for your product?',crossLink:'Explore websites',crossHref:'/websites/'},
 de:{title:'Du hast die Idee. Ich baue dein Projekt.',lead:'Apps, Web-Apps, interne Tools, Automationen und MVPs – von der ersten Struktur bis zum fertigen, nutzbaren Produkt.',badge:'Produktentwicklung mit Vantura',services:[['Apps & Web-Apps','Produkte für Mobile und Web – responsiv, schnell und auf echte Nutzung ausgelegt.',Smartphone],['MVPs & Prototypen','Eine Idee wird ohne monatelange Vorarbeit zu einer testbaren ersten Version.',Blocks],['Automationen','Abläufe, Schnittstellen und KI-Workflows reduzieren manuelle Arbeit.',Workflow],['Interne Tools','Dashboards, Kalkulatoren und Portale passend zum Prozess.',Gauge],['Projekt-Rettung','Halbfertige oder festgefahrene Projekte analysieren, stabilisieren und fertigstellen.',LifeBuoy],['KI-Features','Sinnvolle KI-Funktionen, Agenten und lokale Modelle integrieren.',Bot]],process:'Klarer Prozess. Frühe Ergebnisse.',steps:[['01','Verstehen','Wir klären Ziel, Nutzer und was die erste gute Version können muss.'],['02','Planen & prototypisieren','Du erhältst einen klaren Umfang, Nutzerfluss, technische Richtung und früh ein sichtbares Konzept.'],['03','Gestalten & bauen','Ich entwickle in kurzen Etappen und zeige früh nutzbare Ergebnisse.'],['04','Veröffentlichen & betreuen','Deployment, Einrichtung, Übergabe und auf Wunsch laufende Betreuung.']],cta:'Erzähl mir, was dein Projekt können soll.',button:'Idee besprechen',selected:'Ausgewählte Projekte',selectedLead:'Live-Produkte, interne Systeme und fokussierte Experimente.',cross:'Dein Produkt braucht zusätzlich einen starken öffentlichen Auftritt?',crossLink:'Websites ansehen',crossHref:'/de/websites/'}
} as const

const websites = {
 en:{title:'Websites that do more than look good.',lead:'Modern websites for small businesses, hospitality and local service providers — clearly positioned, mobile-first and ready to generate enquiries.',badge:'Vantura Website Studio',services:[['Individual design','A distinct visual identity instead of generic template aesthetics.',LayoutTemplate],['Mobile first','Clean usability across smartphones, tablets and desktops.',Smartphone],['Clear conversion paths','Strong structure, understandable copy and focused calls to action.',Globe2],['Launch included','Technical setup, deployment, domain support and clean handover.',Rocket]],process:'The website sprint.',steps:[['01','Position','Clarify the offer, audience and primary action.'],['02','Design','Create structure, copy direction and a fitting visual system.'],['03','Build','Implement a fast, responsive and accessible website.'],['04','Launch','Publish, connect the domain and hand everything over.']],cta:'Your website can start small and still look professional.',button:'Discuss your website',selected:'Selected website work',selectedLead:'Live sites and clearly labelled design concepts from the Vantura studio.',cross:'Need more than a website?',crossLink:'Explore product development',crossHref:'/projects/'},
 de:{title:'Websites, die nicht nur gut aussehen.',lead:'Moderne Websites für kleine Unternehmen, Gastronomie und lokale Dienstleister – klar positioniert, mobil optimiert und bereit für echte Anfragen.',badge:'Vantura Website Studio',services:[['Individuelles Design','Ein eigener Auftritt statt austauschbarer Baukasten-Optik.',LayoutTemplate],['Mobile First','Saubere Nutzung auf Smartphone, Tablet und Desktop.',Smartphone],['Klare Wege zur Anfrage','Verständliche Texte, gute Struktur und starke Handlungsaufforderungen.',Globe2],['Launch inklusive','Technische Einrichtung, Veröffentlichung, Domain und Übergabe.',Rocket]],process:'Der Website-Sprint.',steps:[['01','Positionieren','Angebot, Zielgruppe und wichtigste Handlung klären.'],['02','Gestalten','Struktur, Text-Richtung und passendes Design entwickeln.'],['03','Bauen','Eine schnelle, responsive und zugängliche Website umsetzen.'],['04','Veröffentlichen','Domain verbinden, live stellen und sauber übergeben.']],cta:'Deine Website kann klein starten und trotzdem professionell wirken.',button:'Website besprechen',selected:'Ausgewählte Websites',selectedLead:'Live-Seiten und klar gekennzeichnete Designkonzepte aus dem Vantura Studio.',cross:'Du brauchst mehr als eine Website?',crossLink:'Produktentwicklung ansehen',crossHref:'/de/projects/'}
} as const

const examples = {
 project: {
  en:[
   {name:'Grace',status:'Live product',kind:'AI workspace',description:'A cross-platform workspace for orchestrating AI agents, tools and local models with a strong focus on privacy and practical workflows.',stack:['Next.js','React Native','AI agents','Local models'],href:'https://meet-grace.com',accent:'from-violet-100 via-white to-blue-100'},
   {name:'HotCold',status:'In development',kind:'Mobile app',description:'A focused React Native product concept built around fast interaction, simple states and a clean mobile-first experience.',stack:['React Native','Expo','Supabase'],accent:'from-rose-100 via-white to-orange-100'},
   {name:'Heimdal',status:'Prototype',kind:'Smart home',description:'A privacy-aware smart-home interface concept for bringing devices, routines and useful household information into one clear surface.',stack:['App design','Automation','Local first'],accent:'from-emerald-100 via-white to-cyan-100'},
   {name:'Internal calculators',status:'Client work',kind:'Business tools',description:'Custom calculators, reporting systems and operational tools that replace fragmented spreadsheets with clearer decision flows.',stack:['Next.js','Power BI','Excel','Data models'],accent:'from-blue-100 via-white to-slate-100'}
  ],
  de:[
   {name:'Grace',status:'Live-Produkt',kind:'AI Workspace',description:'Ein plattformübergreifender Workspace zur Orchestrierung von AI Agents, Tools und lokalen Modellen – mit Fokus auf Datenschutz und echte Arbeitsabläufe.',stack:['Next.js','React Native','AI Agents','Lokale Modelle'],href:'https://meet-grace.com',accent:'from-violet-100 via-white to-blue-100'},
   {name:'HotCold',status:'In Entwicklung',kind:'Mobile App',description:'Ein fokussiertes React-Native-Produktkonzept mit schneller Interaktion, klaren Zuständen und einer sauberen Mobile-First-Erfahrung.',stack:['React Native','Expo','Supabase'],accent:'from-rose-100 via-white to-orange-100'},
   {name:'Heimdal',status:'Prototyp',kind:'Smart Home',description:'Ein datenschutzorientiertes Smart-Home-Interface, das Geräte, Routinen und Haushaltsinformationen in einer klaren Oberfläche bündelt.',stack:['App Design','Automation','Local First'],accent:'from-emerald-100 via-white to-cyan-100'},
   {name:'Interne Kalkulatoren',status:'Kundenprojekt',kind:'Business Tools',description:'Individuelle Kalkulatoren, Reporting-Systeme und operative Tools, die fragmentierte Tabellen durch klare Entscheidungswege ersetzen.',stack:['Next.js','Power BI','Excel','Datenmodelle'],accent:'from-blue-100 via-white to-slate-100'}
  ]
 },
 websites: {
  en:[
   {name:'Meet Grace',status:'Live',kind:'Product website',description:'A polished product site that turns a complex AI workspace into a clear, approachable and visually distinctive story.',stack:['Next.js','Responsive','Product storytelling'],href:'https://meet-grace.com',accent:'from-violet-100 via-white to-fuchsia-100'},
   {name:'Recruvia',status:'Concept',kind:'Recruitment platform',description:'A corporate one-page concept for a privacy-first recruitment product running local language models without sending data outside the company.',stack:['Corporate design','One page','Privacy messaging'],accent:'from-sky-100 via-white to-indigo-100'},
   {name:'Hof Zurmühlen',status:'Concept',kind:'Local business',description:'A warm, modern website concept created to make a regional business feel personal, trustworthy and immediately understandable.',stack:['Local SEO','Mobile first','Conversion'],accent:'from-amber-100 via-white to-lime-100'},
   {name:'Fröhlich Gebäudeservice',status:'Concept',kind:'Service business',description:'A clean service-business presence with direct contact paths, clear service hierarchy and strong local positioning.',stack:['One pager','Lead generation','Responsive'],accent:'from-cyan-100 via-white to-blue-100'},
   {name:'St. Pauli Dartpiraten',status:'Community work',kind:'Club website',description:'A characterful community site designed around identity, accessibility and quick access to the information members actually need.',stack:['Community','Content structure','Responsive'],accent:'from-red-100 via-white to-slate-100'},
   {name:'Vantura Portfolio',status:'Live',kind:'Studio portfolio',description:'An editorial portfolio presenting concepts and interfaces without turning the work into a generic gallery.',stack:['Next.js','Editorial design','Motion'],href:'/rem0/portfolio/',accent:'from-slate-100 via-white to-blue-100'}
  ],
  de:[
   {name:'Meet Grace',status:'Live',kind:'Produktwebsite',description:'Eine hochwertige Produktseite, die einen komplexen AI Workspace in eine klare, zugängliche und visuell eigenständige Geschichte übersetzt.',stack:['Next.js','Responsive','Product Storytelling'],href:'https://meet-grace.com',accent:'from-violet-100 via-white to-fuchsia-100'},
   {name:'Recruvia',status:'Konzept',kind:'Recruitment-Plattform',description:'Ein Corporate-One-Pager für ein datenschutzorientiertes Recruiting-Produkt mit lokalen Sprachmodellen und vollständig interner Datenverarbeitung.',stack:['Corporate Design','One Page','Privacy Messaging'],accent:'from-sky-100 via-white to-indigo-100'},
   {name:'Hof Zurmühlen',status:'Konzept',kind:'Lokales Unternehmen',description:'Ein warmes, modernes Website-Konzept, das einen regionalen Betrieb persönlich, vertrauenswürdig und sofort verständlich präsentiert.',stack:['Local SEO','Mobile First','Conversion'],accent:'from-amber-100 via-white to-lime-100'},
   {name:'Fröhlich Gebäudeservice',status:'Konzept',kind:'Dienstleister',description:'Ein klarer Auftritt mit direkten Kontaktwegen, verständlicher Leistungsstruktur und starker lokaler Positionierung.',stack:['One Pager','Lead Generation','Responsive'],accent:'from-cyan-100 via-white to-blue-100'},
   {name:'St. Pauli Dartpiraten',status:'Community-Projekt',kind:'Vereinswebsite',description:'Eine charakterstarke Community-Seite mit klarer Identität und schnellem Zugang zu den Informationen, die Mitglieder wirklich brauchen.',stack:['Community','Content-Struktur','Responsive'],accent:'from-red-100 via-white to-slate-100'},
   {name:'Vantura Portfolio',status:'Live',kind:'Studio-Portfolio',description:'Ein redaktionelles Portfolio, das Konzepte und Interfaces zeigt, ohne die Arbeiten zu einer austauschbaren Galerie zu machen.',stack:['Next.js','Editorial Design','Motion'],href:'/rem0/portfolio/',accent:'from-slate-100 via-white to-blue-100'}
  ]
 }
} as const

function WorkGrid({locale,type}:{locale:'en'|'de';type:'project'|'websites'}){
 const items=examples[type][locale]
 return <section className="border-y border-line bg-paper"><div className="mx-auto max-w-6xl px-6 py-20 lg:px-8 lg:py-28"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-600">Built by Vantura</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">{(type==='project'?project:websites)[locale].selected}</h2><p className="mt-5 text-lg leading-8 text-muted">{(type==='project'?project:websites)[locale].selectedLead}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{items.map((item,index)=>{const card=<article className="group overflow-hidden rounded-[30px] border border-line bg-white shadow-[0_18px_50px_rgba(15,23,42,.05)] transition duration-500 hover:-translate-y-1 hover:shadow-[0_28px_70px_rgba(15,23,42,.1)]"><div className={`relative h-56 bg-gradient-to-br ${item.accent} p-6`}><div className="absolute inset-6 rounded-[24px] border border-white/70 bg-white/55 shadow-xl backdrop-blur"><div className="flex h-full flex-col justify-between p-5"><div className="flex items-center justify-between"><span className="rounded-full border border-white bg-white/80 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.16em]">{item.status}</span><span className="text-xs font-medium text-muted">0{index+1}</span></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-muted">{item.kind}</p><h3 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{item.name}</h3></div></div></div></div><div className="p-7"><p className="leading-7 text-muted">{item.description}</p><div className="mt-6 flex flex-wrap gap-2">{item.stack.map(tag=><span key={tag} className="rounded-full bg-paper px-3 py-1.5 text-xs font-medium">{tag}</span>)}</div>{item.href&&<div className="mt-7 flex items-center gap-2 text-sm font-semibold">{locale==='de'?'Ansehen':'View project'}<ArrowUpRight size={16}/></div>}</div></article>;return item.href?<Link key={item.name} href={item.href} target={item.href.startsWith('http')?'_blank':undefined} rel={item.href.startsWith('http')?'noreferrer':undefined}>{card}</Link>:<div key={item.name}>{card}</div>})}</div></div></section>
}

export function LocalizedServicePage({locale,type}:{locale:'en'|'de';type:'project'|'websites'}){
 const isProject=type==='project'
 const t=(isProject?project:websites)[locale]
 const prefix=locale==='de'?'/de':''
 const contact=`mailto:hello@vantura-studios.com?subject=${encodeURIComponent(isProject?(locale==='de'?'Projektanfrage':'Project enquiry'):(locale==='de'?'Website-Anfrage':'Website enquiry'))}`
 return <div className="min-h-screen bg-white text-ink"><LanguageRedirect locale={locale}/>
  <header className="border-b border-line bg-white/90 backdrop-blur"><nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6 lg:px-8"><Link href={`${prefix}/`} className="text-[17px] font-semibold">Vantura</Link><div className="flex items-center gap-3"><LanguageSwitch locale={locale}/><a href={contact} className="hidden rounded-full bg-ink px-4 py-2 text-sm font-medium text-white sm:block">{t.button}</a></div></nav></header>
  <main><section className="overflow-hidden border-b border-line bg-paper"><div className="mx-auto grid max-w-6xl gap-14 px-6 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-line bg-white px-3 py-1.5 text-xs font-semibold uppercase tracking-[.16em] text-muted">{isProject?<Code2 size={14}/>:<Globe2 size={14}/>} {t.badge}</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.05em] sm:text-7xl">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">{t.lead}</p><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.button}<ArrowRight size={17}/></a></div><div className="rounded-[30px] bg-ink p-8 text-white shadow-2xl"><p className="text-xs uppercase tracking-[.16em] text-white/50">Vantura Build System</p><div className="mt-8 space-y-3">{t.steps.slice(0,3).map(([n,a])=><div key={n} className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/50">{n}</p><p className="mt-1 font-semibold">{a}</p></div>)}</div></div></div></section>
  <WorkGrid locale={locale} type={type}/>
  <section className="mx-auto max-w-6xl px-6 py-20 lg:px-8 lg:py-28"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{t.services.map(([a,b,I])=><article key={a as string} className="rounded-[26px] border border-line p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-paper"><I size={20}/></span><h2 className="mt-6 text-xl font-semibold">{a}</h2><p className="mt-3 leading-7 text-muted">{b}</p></article>)}</div></section>
  <section className="bg-ink py-20 text-white"><div className="mx-auto max-w-6xl px-6 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.process}</h2><div className="mt-10 divide-y divide-white/10 border-y border-white/10">{t.steps.map(([n,a,b])=><div key={n} className="grid gap-3 py-6 sm:grid-cols-[56px_180px_1fr]"><p className="text-white/35">{n}</p><p className="font-semibold">{a}</p><p className="text-white/60">{b}</p></div>)}</div></div></section>
  {isProject&&<ProjectDetails locale={locale}/>}<section className="border-b border-line bg-white px-6 py-20"><div className="mx-auto flex max-w-6xl flex-col gap-6 rounded-[30px] bg-paper p-8 sm:flex-row sm:items-center sm:justify-between lg:p-12"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-muted">Vantura Studio</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{t.cross}</h2></div><Link href={t.crossHref} className="inline-flex items-center gap-2 font-semibold">{t.crossLink}<ArrowRight size={18}/></Link></div></section><section className="bg-paper px-6 py-24 text-center"><ShieldCheck className="mx-auto"/><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold sm:text-6xl">{t.cta}</h2><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.button}<ArrowRight size={17}/></a></section></main>
 </div>
}
