import Link from 'next/link'
import { ArrowRight, BarChart3, FileSpreadsheet, LayoutDashboard, LineChart, Linkedin, RefreshCw, ShieldCheck, Workflow } from 'lucide-react'
import { LanguageSwitch } from './LanguageSwitch'
import { HeroDashboard } from './dashboard/HeroDashboard'
import { ShowcaseDashboard } from './dashboard/ShowcaseDashboard'

const text = {
  en: {
    call:'Free consultation', demoCta:'Try the interactive demo', badge:'Reporting · Dashboards · Automation', hero:'Better decisions start with better data.', intro:'We build reporting, dashboard and automation solutions for companies that want to understand what is happening in their business — faster and with less manual work.',
    problem:'Your data is there. The answers are not.', problemText:'Numbers are scattered across spreadsheets and systems, arrive too late and require too much manual work.',
    cards:[['Spreadsheet chaos','Conflicting files and values make reliable decisions difficult.',FileSpreadsheet],['Late numbers','Reports arrive after the moment to act has passed.',RefreshCw],['Manual work','Copying, formatting and distributing reports consumes valuable time.',Workflow],['Missing overview','No system provides one reliable view of the business.',BarChart3]],
    solution:'Clarity instead of another tool.', solutionText:'Every solution starts with a concrete business question. Technology is only the means to answer it.',
    services:[['Management dashboards','Revenue, cost, pipeline and budget in one current interface.',LayoutDashboard],['Reporting automation','Reports assemble, validate and distribute themselves.',Workflow],['Forecasting & planning','Transparent scenarios and early warning for deviations.',LineChart],['Custom data solutions','Interfaces and internal tools built around your process.',ShieldCheck]],
    process:'From the first conversation to a working system.', steps:[['01','Discovery','We clarify goals, systems and the decisions the solution must support.'],['02','Concept','You receive a focused scope, technical direction and clear proposal.'],['03','Build','We work in short iterations and show usable results early.'],['04','Handover','Documentation, onboarding and optional ongoing support.']],
    why:'Business understanding meets software development.', whyText:'Vantura combines reporting, forecasting and investment experience with practical software development. The result is a maintainable decision system your team can actually use.',
    faq:'Frequently asked questions', faqs:[['Do we need to replace our systems?','No. We connect the tools and data sources you already use.'],['How quickly do we see results?','A first usable version is typically available within two to four weeks.'],['What does a project cost?','After a short analysis you receive a clear scope and fixed-price proposal.']],
    cta:'Turn your data into better decisions.', ctaText:'Tell us where reporting, planning or manual processes slow your team down.', home:'Overview',
    proofLine:'30 minutes · no obligation · direct contact with the person who builds your solution',
    clientsEyebrow:'Selected clients', clientsTitle:'Trusted with real projects.', clientsLead:'Selected organisations and products Vantura has worked with — from reporting systems to software and digital presence.',
    demoLabel:'Interactive design study · anonymised sample data',
    caseEyebrow:'Case study · Operations Hub', caseTitle:'From scattered data sources to one operational management system.', caseLead:'Built as a working reference implementation for an operations reporting workflow — with a clear path from structured source data to decisions, contracts and partner evaluation.',
    caseSteps:[['Starting point','Performance, pacing, contracts and partner evaluations lived in separate views and files.'],['Implementation','A responsive operations hub combining structured data, KPI dashboards, partner details, contract management and score cards.'],['Deliverable','A white-label system with roles, audit log, validation and an optional self-hosted Docker deployment.']],
    caseFeatures:['Flexible data integration','Management summary and pacing','Contracts and score cards','Roles, validation and audit log','White-label and self-hosting'], caseDemo:'Explore the interactive demo',
    workEyebrow:'Selected work & experience', workTitle:'Real work, clearly labelled.', workLead:'Client work, reference implementations and product concepts are deliberately distinguished — so you can see what is operational work and what demonstrates the range of the studio.',
    work:[['Weischer.Cinema Deutschland','Ongoing client work','Reporting, calculation tools and internal decision systems.'],['Grace AI Assistant','Product development','A private multi-agent workspace spanning desktop, mobile and local AI workflows.'],['Fröhlich-Nord','Reporting, sales & marketing','Reporting, sales support, marketing and digital presence for a regional building-services company.'],['RGH-Nord','Client website','Website and service presentation for a northern German building-services provider.'],['Recruvia','Reporting & advertising consulting','Reporting, performance visibility and advertising consulting for a recruiting platform.']],
    founderEyebrow:'Your contact', founderTitle:'Built and delivered by Jonathan Kokalj.', founderText:'Vantura is an owner-led studio based near Hamburg. Jonathan combines reporting and forecasting experience from media and investment environments with practical software development — from the data model to the finished interface.', founderLink:'View developer portfolio', linkedin:'LinkedIn profile',
    trustTitle:'Clear ownership from day one.', trustPoints:['Direct contact without sales handovers','Defined scope and fixed-price proposal','Documentation and structured handover','Your system and business logic remain transparent'],
    legal:'Legal notice', privacy:'Privacy', portfolio:'Developer portfolio', demoDisclaimer:'All figures and company names shown in dashboard visuals are fictional sample data.'
  },
  de: {
    call:'Kostenloses Erstgespräch', demoCta:'Interaktive Demo ausprobieren', badge:'Reporting · Dashboards · Automatisierung', hero:'Bessere Entscheidungen beginnen mit besseren Daten.', intro:'Wir entwickeln Reporting-, Dashboard- und Automatisierungslösungen für Unternehmen, die schneller verstehen wollen, was in ihrem Geschäft passiert.',
    problem:'Ihre Daten sind da. Nur die Antworten fehlen.', problemText:'Zahlen liegen verstreut in Excel-Dateien und Systemen, kommen zu spät und verursachen zu viel manuelle Arbeit.',
    cards:[['Excel-Chaos','Widersprüchliche Dateien und Werte erschweren verlässliche Entscheidungen.',FileSpreadsheet],['Verspätete Zahlen','Berichte kommen, wenn der Zeitpunkt zum Handeln bereits vorbei ist.',RefreshCw],['Manuelle Arbeit','Kopieren, Formatieren und Verteilen kostet wertvolle Zeit.',Workflow],['Fehlender Überblick','Kein System zeigt eine verlässliche Gesamtsicht.',BarChart3]],
    solution:'Klarheit statt noch eines Tools.', solutionText:'Jede Lösung beginnt mit einer konkreten Geschäftsfrage. Technologie ist nur das Mittel, sie zu beantworten.',
    services:[['Management-Dashboards','Umsatz, Kosten, Pipeline und Budget in einer aktuellen Oberfläche.',LayoutDashboard],['Reporting-Automatisierung','Berichte erstellen, prüfen und verteilen sich automatisch.',Workflow],['Forecasting & Planung','Nachvollziehbare Szenarien und Frühwarnung bei Abweichungen.',LineChart],['Individuelle Datenlösungen','Schnittstellen und interne Tools passend zum Prozess.',ShieldCheck]],
    process:'Vom ersten Gespräch zum laufenden System.', steps:[['01','Erstgespräch','Wir klären Ziele, Systeme und die Entscheidungen, die unterstützt werden sollen.'],['02','Konzept','Sie erhalten einen klaren Umfang, technische Richtung und ein Angebot.'],['03','Umsetzung','Wir arbeiten in kurzen Etappen und zeigen früh nutzbare Ergebnisse.'],['04','Übergabe','Dokumentation, Einweisung und optionale Betreuung.']],
    why:'Business-Verständnis trifft Softwareentwicklung.', whyText:'Vantura verbindet Reporting-, Forecasting- und Investment-Erfahrung mit praktischer Softwareentwicklung. Das Ergebnis ist ein wartbares Entscheidungssystem, das im Alltag genutzt wird.',
    faq:'Häufige Fragen', faqs:[['Müssen wir unsere Systeme wechseln?','Nein. Wir binden bestehende Werkzeuge und Datenquellen an.'],['Wie schnell sehen wir Ergebnisse?','Eine erste nutzbare Version ist typischerweise nach zwei bis vier Wochen verfügbar.'],['Was kostet ein Projekt?','Nach einer kurzen Analyse erhalten Sie einen klaren Umfang und Festpreis.']],
    cta:'Machen Sie aus Daten bessere Entscheidungen.', ctaText:'Erzählen Sie uns, wo Reporting, Planung oder manuelle Prozesse Ihr Team ausbremsen.', home:'Übersicht',
    proofLine:'30 Minuten · unverbindlich · direkter Kontakt mit der Person, die Ihre Lösung baut',
    clientsEyebrow:'Ausgewählte Kunden', clientsTitle:'Vertrauen durch echte Projekte.', clientsLead:'Ausgewählte Unternehmen und Produkte, mit denen Vantura gearbeitet hat – von Reporting-Systemen bis zu Software und digitalem Auftritt.',
    demoLabel:'Interaktive Designstudie · anonymisierte Beispieldaten',
    caseEyebrow:'Case Study · Operations Hub', caseTitle:'Aus verteilten Datenquellen wird ein steuerbares Management-System.', caseLead:'Als funktionierende Referenz für einen operativen Reporting-Prozess entwickelt – von strukturierten Quelldaten bis zu Entscheidungen, Verträgen und Partnerbewertungen.',
    caseSteps:[['Ausgangslage','Performance, Pacing, Verträge und Partnerbewertungen lagen in getrennten Ansichten und Dateien.'],['Umsetzung','Ein responsiver Operations Hub mit strukturierten Daten, KPI-Dashboard, Partnerdetails, Vertragsmanagement und Scorecards.'],['Lieferumfang','Ein White-Label-System mit Rollen, Audit-Log, Validierung und optionalem Self-Hosting per Docker.']],
    caseFeatures:['Flexible Datenanbindung','Management Summary und Pacing','Verträge und Scorecards','Rollen, Validierung und Audit-Log','White-Label und Self-Hosting'], caseDemo:'Interaktive Demo ausprobieren',
    workEyebrow:'Ausgewählte Arbeiten & Erfahrung', workTitle:'Echte Arbeit, klar eingeordnet.', workLead:'Kundenarbeit, Referenzimplementierungen und Produktkonzepte werden bewusst unterschieden – damit nachvollziehbar bleibt, was operativ eingesetzt wird und was die Bandbreite des Studios zeigt.',
    work:[['Weischer.Cinema Deutschland','Laufendes Kundenprojekt','Reporting, Kalkulationstools und interne Entscheidungssysteme.'],['Grace AI Assistant','Produktentwicklung','Ein privater Multi-Agent-Workspace für Desktop, Mobile und lokale KI-Workflows.'],['Fröhlich-Nord','Reporting, Vertrieb & Marketing','Reporting, Vertriebsunterstützung, Marketing und digitaler Auftritt für einen regionalen Gebäudedienstleister.'],['RGH-Nord','Kundenwebsite','Website und Leistungspräsentation für einen norddeutschen Gebäudedienstleister.'],['Recruvia','Reporting & Werbeberatung','Reporting, Performance-Übersichten und Werbeberatung für eine Recruiting-Plattform.']],
    founderEyebrow:'Ihr Ansprechpartner', founderTitle:'Konzipiert und umgesetzt von Jonathan Kokalj.', founderText:'Vantura ist ein inhabergeführtes Studio aus dem Raum Hamburg. Jonathan verbindet Reporting- und Forecasting-Erfahrung aus Media- und Investment-Umfeldern mit praktischer Softwareentwicklung – vom Datenmodell bis zur fertigen Oberfläche.', founderLink:'Entwickler-Portfolio ansehen', linkedin:'LinkedIn-Profil',
    trustTitle:'Klare Verantwortung vom ersten Tag an.', trustPoints:['Direkter Kontakt ohne Sales-Übergaben','Definierter Umfang und Festpreisangebot','Dokumentation und strukturierte Übergabe','System und Geschäftslogik bleiben transparent'],
    legal:'Impressum', privacy:'Datenschutz', portfolio:'Entwickler-Portfolio', demoDisclaimer:'Alle in den Dashboard-Visualisierungen gezeigten Zahlen und Unternehmensnamen sind fiktive Beispieldaten.'
  }
 } as const

const CUSTOMERS = [
 {name:'Weischer.Cinema Deutschland',href:'https://www.weischer-cinema.de/',logo:'/customer-logos/weischer-cinema.svg'},
 {name:'Grace AI Assistant',href:'https://meet-grace.com/',logo:'/customer-logos/grace.svg'},
 {name:'Fröhlich-Nord',href:'https://www.froehlich-nord.de/',logo:'/customer-logos/froehlich-nord.svg'},
 {name:'RGH-Nord',href:'https://rgh-nord.com/',logo:'/customer-logos/rgh-nord.svg'},
 {name:'Recruvia',href:'https://recruvia.org/',logo:'/customer-logos/recruvia.svg'},
] as const

export function LocalizedReporting({locale}:{locale:'en'|'de'}){
 const t=text[locale], prefix=locale==='de'?'/de':'', basePath=process.env.NEXT_PUBLIC_BASE_PATH ?? '', demoHref=`${prefix}/reporting/demo/`
 const contact=`mailto:jk@vantura-studios.com?subject=${encodeURIComponent(locale==='de'?'Erstgespräch: Reporting & Daten':'Intro call: Reporting & data')}`
 return <div className="min-h-screen bg-white text-ink">
  <header className="sticky top-0 z-50 border-b border-line bg-white/90 backdrop-blur"><nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href={`${prefix}/`} className="flex min-w-0 items-center gap-2"><img src={basePath+'/brand/vantura-logo.png'} alt="" className="h-9 w-9 shrink-0 object-contain"/><span className="truncate text-[15px] font-semibold sm:text-[17px]">Vantura Studios</span></Link><div className="ml-3 flex shrink-0 items-center gap-3"><Link href={`${prefix}/`} className="hidden text-sm text-muted sm:block">{t.home}</Link><LanguageSwitch locale={locale}/><a href={contact} className="hidden rounded-full bg-ink px-4 py-2 text-sm font-medium text-white sm:block">{t.call}</a></div></nav></header>
  <main><section className="bg-paper"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 sm:px-6 sm:py-20 lg:grid-cols-2 lg:items-center lg:gap-14 lg:px-8 lg:py-28"><div><p className="inline-flex rounded-full border border-line bg-white px-3 py-1.5 text-xs text-muted sm:text-sm">{t.badge}</p><h1 className="mt-6 text-4xl font-semibold tracking-[-.045em] sm:mt-7 sm:text-6xl lg:text-7xl">{t.hero}</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted sm:mt-7 sm:text-lg sm:leading-8">{t.intro}</p><a href={contact} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white sm:mt-9 sm:w-auto">{t.call}<ArrowRight size={16}/></a><p className="mt-5 text-sm leading-6 text-muted">{t.proofLine}</p></div><HeroDashboard/></div></section>
  <section className="border-y border-line bg-white py-16"><div className="mx-auto max-w-6xl px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">{t.clientsEyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">{t.clientsTitle}</h2><p className="mt-4 leading-7 text-muted">{t.clientsLead}</p></div><div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{CUSTOMERS.map(customer=><a key={customer.name} href={customer.href} target="_blank" rel="noreferrer" aria-label={customer.name} className="group flex h-28 items-center justify-center rounded-2xl border border-line bg-paper px-5 transition-all duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-card"><img src={basePath+customer.logo} alt={customer.name} className="max-h-16 w-full object-contain opacity-75 grayscale transition-all duration-300 group-hover:opacity-100 group-hover:grayscale-0"/></a>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-16 sm:px-6 sm:py-24 lg:px-8"><h2 className="text-3xl font-semibold tracking-[-.03em] sm:text-5xl">{t.problem}</h2><p className="mt-5 max-w-3xl text-base leading-7 text-muted sm:text-lg sm:leading-8">{t.problemText}</p><Link href={demoHref} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full border border-line bg-white px-6 py-3.5 text-sm font-semibold text-ink transition hover:border-ink sm:w-auto">{t.demoCta}<ArrowRight size={16}/></Link><div className="mt-10 grid gap-4 sm:mt-12 sm:grid-cols-2 sm:gap-5 lg:grid-cols-4">{t.cards.map(([a,b,I])=><article key={a as string} className="rounded-2xl border border-line p-5 sm:p-6"><I size={20}/><h3 className="mt-5 font-semibold">{a}</h3><p className="mt-2 text-sm leading-6 text-muted">{b}</p></article>)}</div></section>
  <section className="bg-paper py-24"><div className="mx-auto max-w-6xl px-6 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.solution}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{t.solutionText}</p><div className="mt-12 grid gap-6 md:grid-cols-2">{t.services.map(([a,b,I])=><article key={a as string} className="rounded-2xl border border-line bg-white p-8"><I size={22}/><h3 className="mt-5 text-xl font-semibold">{a}</h3><p className="mt-3 leading-7 text-muted">{b}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-6 py-24 lg:px-8">
   <div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="inline-flex w-fit rounded-full border border-line bg-paper px-3 py-1.5 text-xs font-semibold uppercase tracking-[.14em] text-muted">{t.demoLabel}</p><p className="max-w-xl text-xs leading-5 text-muted sm:text-right">{t.demoDisclaimer}</p></div>
   <ShowcaseDashboard/>
  </section>
  <section className="bg-paper py-24"><div className="mx-auto max-w-6xl px-6 lg:px-8">
   <p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">{t.caseEyebrow}</p>
   <div className="mt-5 grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{t.caseTitle}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{t.caseLead}</p></div><div className="flex flex-wrap gap-2">{t.caseFeatures.map(item=><span key={item} className="rounded-full border border-line bg-white px-3 py-1.5 text-xs font-medium text-muted">{item}</span>)}</div></div>
   <div className="mt-12 grid gap-5 md:grid-cols-3">{t.caseSteps.map(([title,description],index)=><article key={title} className="rounded-2xl border border-line bg-white p-7"><p className="text-xs font-semibold text-muted">0{index+1}</p><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{description}</p></article>)}</div>
   <Link href={demoHref} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-ink">{t.caseDemo}<ArrowRight size={16}/></Link>
  </div></section>
  <section className="mx-auto max-w-6xl px-6 py-24 lg:px-8">
   <p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">{t.workEyebrow}</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{t.workTitle}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{t.workLead}</p>
   <div className="mt-12 grid gap-5 sm:grid-cols-2">{t.work.map(([name,status,description])=><article key={name} className="rounded-2xl border border-line p-7"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted">{status}</p><h3 className="mt-4 text-xl font-semibold">{name}</h3><p className="mt-3 leading-7 text-muted">{description}</p></article>)}</div>
  </section>
  <section className="bg-ink py-24 text-white"><div className="mx-auto max-w-6xl px-6 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.process}</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{t.steps.map(([n,a,b])=><article key={n} className="rounded-2xl border border-white/15 p-6"><p className="text-white/40">{n}</p><h3 className="mt-5 font-semibold">{a}</h3><p className="mt-3 text-sm leading-6 text-white/60">{b}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-6 py-24 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.why}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">{t.whyText}</p></section>
  <section className="border-y border-line bg-white py-24"><div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8">
   <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">{t.founderEyebrow}</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{t.founderTitle}</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">{t.founderText}</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3"><Link href="/rem0/portfolio/" className="inline-flex items-center gap-2 text-sm font-semibold">{t.founderLink}<ArrowRight size={16}/></Link><a href="https://www.linkedin.com/in/jonathan-kokalj/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold"><Linkedin size={16}/>{t.linkedin}<ArrowRight size={16}/></a></div></div>
   <div className="rounded-2xl border border-line bg-paper p-7 sm:p-8"><div className="flex items-center gap-4"><img src={basePath+'/brand/jonathan-kokalj.jpg'} alt="Jonathan Kokalj" className="h-20 w-20 rounded-2xl object-cover"/><div><p className="font-semibold">Jonathan Kokalj</p><p className="text-sm text-muted">Founder · BI Consultant · Software Developer</p></div></div><h3 className="mt-8 text-xl font-semibold">{t.trustTitle}</h3><ul className="mt-5 space-y-3">{t.trustPoints.map(item=><li key={item} className="flex gap-3 text-sm leading-6 text-muted"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-accent"/><span>{item}</span></li>)}</ul></div>
  </div></section>
  <section className="bg-paper py-24"><div className="mx-auto max-w-4xl px-6"><h2 className="text-4xl font-semibold">{t.faq}</h2><div className="mt-10 divide-y divide-line border-y border-line">{t.faqs.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 leading-7 text-muted">{a}</p></details>)}</div></div></section>
  <section className="px-6 py-24 text-center"><h2 className="text-4xl font-semibold sm:text-6xl">{t.cta}</h2><p className="mx-auto mt-6 max-w-2xl text-lg text-muted">{t.ctaText}</p><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.call}<ArrowRight size={16}/></a></section></main>
  <footer className="border-t border-line bg-paper"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-6 py-10 text-sm text-muted sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><p className="font-semibold text-ink">Vantura Studios</p><p className="mt-1">Inh. Jonathan Kokalj · Rellingen, Deutschland</p></div><nav className="flex flex-wrap gap-x-6 gap-y-3"><Link href="/rem0/portfolio/" className="hover:text-ink">{t.portfolio}</Link><Link href="/impressum/" className="hover:text-ink">{t.legal}</Link><Link href="/datenschutz/" className="hover:text-ink">{t.privacy}</Link></nav></div></footer>
 </div>
}
