import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Brush, FileImage, Globe2, Image, Layers3, Megaphone, MonitorSmartphone, Palette, PanelsTopLeft, Sparkles } from 'lucide-react'
import { LanguageRedirect } from './LanguageRedirect'
import { LanguageSwitch } from './LanguageSwitch'

const copy = {
  en: {
    badge: 'Vantura Design Studio', title: 'Design systems for brands that need to look established.', lead: 'Web design, campaigns, ads, banners and sales assets — built as one coherent visual system instead of disconnected single pieces.', primary: 'Discuss a design project', secondary: 'Explore web design',
    introTitle: 'One idea should work everywhere.', introLead: 'The website, paid campaign, sales deck and social assets should feel like the same brand — even when formats, channels and audiences change.',
    services: [['Web design','Digital experiences with clear hierarchy, responsive layouts and a strong path to action.',Globe2],['Campaign creative','A visual direction translated into paid social, display and launch formats.',Megaphone],['Social systems','Reusable posts, stories, templates and editorial formats for ongoing communication.',Image],['Banners & advertising','Digital banners, event graphics, campaign headers and promotional formats.',FileImage],['Brand foundations','Colour, typography, layout principles and practical rules for consistency.',Palette],['Sales design','Pitch decks, proposals, one-pagers and materials that make complex offers easy to understand.',PanelsTopLeft]],
    portfolioTitle: 'Not isolated assets. Complete visual worlds.', portfolioLead: 'Selected directions showing how one core idea can expand into a website, campaign and communication system.',
    process: [['01','Position','Clarify audience, message, market context and the action the design must support.'],['02','Direct','Build a visual territory with references, typography, colour and layout behaviour.'],['03','Create','Develop the central experience and adapt it across the required formats.'],['04','Systemise','Deliver reusable components, files and rules so the visual language remains consistent.']],
    formatsTitle: 'Built for real marketing operations.', formatsLead: 'Every project can scale from a focused first package to an ongoing design system.', webTitle: 'Need the complete website?', webLead: 'The dedicated web design page covers positioning, structure, responsive design, implementation and launch.', webButton: 'Open web design', cta: 'Make every touchpoint feel intentional.'
  },
  de: {
    badge: 'Vantura Design Studio', title: 'Designsysteme für Marken, die etabliert wirken müssen.', lead: 'Webdesign, Kampagnen, Ads, Banner und Vertriebsunterlagen – als zusammenhängendes visuelles System statt als Sammlung einzelner Assets.', primary: 'Designprojekt besprechen', secondary: 'Webdesign ansehen',
    introTitle: 'Eine Idee muss überall funktionieren.', introLead: 'Website, Paid Campaign, Sales Deck und Social Assets sollten wie dieselbe Marke wirken – auch wenn sich Formate, Kanäle und Zielgruppen verändern.',
    services: [['Webdesign','Digitale Erlebnisse mit klarer Hierarchie, responsiven Layouts und einem starken Weg zur Handlung.',Globe2],['Kampagnen-Creative','Eine visuelle Richtung, übersetzt in Paid Social, Display und Launch-Formate.',Megaphone],['Social-Systeme','Wiederverwendbare Posts, Stories, Templates und redaktionelle Formate für laufende Kommunikation.',Image],['Banner & Werbung','Digitale Banner, Eventgrafiken, Kampagnenheader und Werbeformate.',FileImage],['Brand Foundations','Farbe, Typografie, Layoutprinzipien und praktische Regeln für Konsistenz.',Palette],['Sales Design','Pitchdecks, Angebote, One-Pager und Unterlagen, die komplexe Leistungen klar vermitteln.',PanelsTopLeft]],
    portfolioTitle: 'Keine Einzelassets. Vollständige visuelle Welten.', portfolioLead: 'Ausgewählte Richtungen, die zeigen, wie sich eine Kernidee in Website, Kampagne und Kommunikation entfaltet.',
    process: [['01','Positionieren','Zielgruppe, Botschaft, Marktumfeld und gewünschte Handlung klären.'],['02','Ausrichten','Ein visuelles Territorium aus Referenzen, Typografie, Farbe und Layoutverhalten entwickeln.'],['03','Gestalten','Das zentrale Erlebnis entwickeln und auf alle benötigten Formate übertragen.'],['04','Systematisieren','Komponenten, Dateien und Regeln liefern, damit die visuelle Sprache konsistent bleibt.']],
    formatsTitle: 'Gebaut für echte Marketingabläufe.', formatsLead: 'Jedes Projekt kann von einem fokussierten Startpaket zu einem laufenden Designsystem wachsen.', webTitle: 'Du brauchst die komplette Website?', webLead: 'Die eigene Webdesign-Seite zeigt Positionierung, Struktur, responsives Design, Umsetzung und Launch im Detail.', webButton: 'Webdesign öffnen', cta: 'Lass jeden Touchpoint bewusst gestaltet wirken.'
  }
} as const

const cases = [
  {name:'Recruvia',type:'Enterprise campaign system',className:'from-blue-600 via-indigo-500 to-cyan-400',href:'/recruvia/'},
  {name:'Grace',type:'Product brand & digital experience',className:'from-violet-600 via-fuchsia-500 to-rose-300',href:'https://meet-grace.com'},
  {name:'Local business campaigns',type:'Web, ads & conversion assets',className:'from-amber-300 via-orange-300 to-rose-300',href:'/websites/'},
]

export function LocalizedDesignPage({ locale }: { locale: 'en' | 'de' }) {
  const t = copy[locale]; const prefix = locale === 'de' ? '/de' : ''; const contact = `mailto:jk@vantura-studios.com?subject=${encodeURIComponent(locale === 'de' ? 'Design-Anfrage' : 'Design enquiry')}`
  return <div className="min-h-screen bg-[#f7f5f2] text-ink"><LanguageRedirect locale={locale}/>
    <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f7f5f2]/90 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6 lg:px-8"><Link href={`${prefix}/`} className="font-semibold tracking-[-.03em]">Vantura Studios</Link><div className="flex items-center gap-3"><LanguageSwitch locale={locale}/><a href={contact} className="hidden rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white sm:block">{t.primary}</a></div></nav></header>
    <main>
      <section className="relative overflow-hidden border-b border-black/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(217,70,239,.14),transparent_28%),radial-gradient(circle_at_20%_80%,rgba(251,191,36,.15),transparent_30%)]"/><div className="relative mx-auto grid min-h-[760px] max-w-7xl gap-14 px-6 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><div className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/80 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.16em]"><Sparkles size={14}/>{t.badge}</div><h1 className="mt-7 max-w-4xl text-5xl font-semibold leading-[.91] tracking-[-.065em] sm:text-7xl lg:text-[88px]">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">{t.lead}</p><div className="mt-9 flex flex-wrap gap-3"><a href={contact} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 text-sm font-semibold text-white">{t.primary}<ArrowRight size={17}/></a><Link href={`${prefix}/websites/`} className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-6 py-3.5 text-sm font-semibold">{t.secondary}<ArrowRight size={17}/></Link></div></div>
        <div className="relative min-h-[600px]"><div className="absolute left-0 top-8 h-[470px] w-[72%] rotate-[-4deg] rounded-[38px] bg-gradient-to-br from-fuchsia-500 to-violet-700 p-7 text-white shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-white/70">Campaign system</p><p className="mt-52 text-5xl font-semibold leading-[.9] tracking-[-.06em]">One idea.<br/>Every format.</p></div><div className="absolute right-0 top-0 h-[380px] w-[55%] rotate-[5deg] rounded-[34px] bg-white p-6 shadow-2xl"><MonitorSmartphone size={26}/><div className="mt-16 rounded-[22px] bg-slate-950 p-5 text-white"><div className="h-3 w-20 rounded-full bg-fuchsia-400"/><div className="mt-16 text-3xl font-semibold tracking-[-.05em]">Digital<br/>experience</div></div></div><div className="absolute bottom-0 right-10 w-[68%] rounded-[32px] bg-amber-300 p-7 shadow-2xl"><Layers3 size={28}/><div className="mt-16 flex items-end justify-between"><p className="text-3xl font-semibold tracking-[-.05em]">Brand language<br/>that scales.</p><span className="text-sm font-semibold">01—24</span></div></div></div></div></section>
      <section className="bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><p className="pt-3 text-xs font-semibold uppercase tracking-[.2em] text-fuchsia-600">Design direction</p><div><h2 className="text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">{t.introTitle}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">{t.introLead}</p></div></div><div className="mt-16 divide-y divide-black/10 border-y border-black/10">{t.services.map(([title,description,Icon],index)=><article key={title} className="grid gap-5 py-7 md:grid-cols-[70px_1fr_1.2fr_auto] md:items-center"><span className="text-xs font-semibold text-black/35">0{index+1}</span><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f7f5f2]"><Icon size={19}/></span><h3 className="text-xl font-semibold">{title}</h3></div><p className="leading-7 text-muted">{description}</p><ArrowUpRight className="hidden text-black/30 md:block"/></article>)}</div></div></section>
      <section className="bg-slate-950 py-24 text-white lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-fuchsia-300">Selected directions</p><h2 className="mt-5 text-4xl font-semibold leading-[.95] tracking-[-.055em] sm:text-6xl">{t.portfolioTitle}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-white/55">{t.portfolioLead}</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{cases.map((item,index)=><Link key={item.name} href={item.href} className="group"><article className="overflow-hidden rounded-[30px] border border-white/10 bg-white/5"><div className={`h-72 bg-gradient-to-br ${item.className} p-6`}><div className="flex h-full flex-col justify-between rounded-[24px] border border-white/30 bg-black/10 p-5 backdrop-blur-sm"><span className="text-xs font-semibold uppercase tracking-[.16em] text-white/70">0{index+1}</span><div><p className="text-sm text-white/65">{item.type}</p><h3 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{item.name}</h3></div></div></div><div className="flex items-center justify-between p-6"><span className="text-sm font-semibold">View system</span><ArrowUpRight className="transition group-hover:-translate-y-1 group-hover:translate-x-1" size={18}/></div></article></Link>)}</div></div></section>
      <section className="py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><Brush/><h2 className="mt-7 text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">{t.formatsTitle}</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted">{t.formatsLead}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[28px] bg-white p-7 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.16em] text-black/35">Launch</p><p className="mt-20 text-2xl font-semibold">Key visual · landing page · ads · social assets</p></div><div className="rounded-[28px] bg-fuchsia-100 p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-fuchsia-700">Campaign</p><p className="mt-20 text-2xl font-semibold">Creative direction · format system · production</p></div><div className="rounded-[28px] bg-amber-200 p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-800">Sales</p><p className="mt-20 text-2xl font-semibold">Decks · one-pagers · proposals · visual storytelling</p></div><div className="rounded-[28px] bg-slate-950 p-7 text-white"><p className="text-xs font-semibold uppercase tracking-[.16em] text-white/45">Ongoing</p><p className="mt-20 text-2xl font-semibold">Creative support · templates · recurring formats</p></div></div></div></section>
      <section className="bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">{locale==='de'?'Erst die Richtung. Dann die Gestaltung.':'Clear direction before decoration.'}</h2><div className="mt-12 divide-y divide-black/10 border-y border-black/10">{t.process.map(([n,title,description])=><div key={n} className="grid gap-3 py-7 sm:grid-cols-[70px_220px_1fr]"><p className="text-black/35">{n}</p><p className="font-semibold">{title}</p><p className="text-muted">{description}</p></div>)}</div></div></section>
      <section className="py-24"><div className="mx-auto flex max-w-7xl flex-col gap-8 rounded-[36px] bg-gradient-to-br from-amber-200 via-white to-fuchsia-100 p-8 sm:flex-row sm:items-center sm:justify-between lg:p-14"><div><Globe2/><h2 className="mt-5 text-3xl font-semibold tracking-[-.05em] sm:text-5xl">{t.webTitle}</h2><p className="mt-4 max-w-2xl leading-7 text-muted">{t.webLead}</p></div><Link href={`${prefix}/websites/`} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 text-sm font-semibold text-white">{t.webButton}<ArrowRight size={17}/></Link></div></section>
      <section className="bg-slate-950 px-6 py-28 text-center text-white"><h2 className="mx-auto max-w-4xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">{t.cta}</h2><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-slate-950">{t.primary}<ArrowRight size={17}/></a></section>
    </main></div>
}