import Link from 'next/link'
import { ArrowRight, BarChart3, Check, FileSpreadsheet, LayoutDashboard, LineChart, RefreshCw, ShieldCheck, Workflow } from 'lucide-react'
import { LanguageRedirect } from './LanguageRedirect'
import { LanguageSwitch } from './LanguageSwitch'
import { HeroDashboard } from './dashboard/HeroDashboard'
import { ShowcaseDashboard } from './dashboard/ShowcaseDashboard'

const text = {
  en: {
    call:'Free consultation', badge:'Reporting · Dashboards · Automation', hero:'Better decisions start with better data.', intro:'We build reporting, dashboard and automation solutions for companies that want to understand what is happening in their business — faster and with less manual work.',
    problem:'Your data is there. The answers are not.', problemText:'Numbers are scattered across spreadsheets and systems, arrive too late and require too much manual work.',
    cards:[['Spreadsheet chaos','Conflicting files and values make reliable decisions difficult.',FileSpreadsheet],['Late numbers','Reports arrive after the moment to act has passed.',RefreshCw],['Manual work','Copying, formatting and distributing reports consumes valuable time.',Workflow],['Missing overview','No system provides one reliable view of the business.',BarChart3]],
    solution:'Clarity instead of another tool.', solutionText:'Every solution starts with a concrete business question. Technology is only the means to answer it.',
    services:[['Management dashboards','Revenue, cost, pipeline and budget in one current interface.',LayoutDashboard],['Reporting automation','Reports assemble, validate and distribute themselves.',Workflow],['Forecasting & planning','Transparent scenarios and early warning for deviations.',LineChart],['Custom data solutions','Interfaces and internal tools built around your process.',ShieldCheck]],
    process:'From the first conversation to a working system.', steps:[['01','Discovery','We clarify goals, systems and the decisions the solution must support.'],['02','Concept','You receive a focused scope, technical direction and clear proposal.'],['03','Build','We work in short iterations and show usable results early.'],['04','Handover','Documentation, onboarding and optional ongoing support.']],
    why:'Business understanding meets software development.', whyText:'Vantura combines reporting, forecasting and investment experience with practical software development. The result is a maintainable decision system your team can actually use.',
    faq:'Frequently asked questions', faqs:[['Do we need to replace our systems?','No. We connect the tools and data sources you already use.'],['How quickly do we see results?','A first usable version is typically available within two to four weeks.'],['What does a project cost?','After a short analysis you receive a clear scope and fixed-price proposal.']],
    cta:'Turn your data into better decisions.', ctaText:'Tell us where reporting, planning or manual processes slow your team down.', projects:'Projects', websites:'Websites', footer:'Reporting, dashboards and automation for companies that want to understand their data.'
  },
  de: {
    call:'Kostenloses Erstgespräch', badge:'Reporting · Dashboards · Automatisierung', hero:'Bessere Entscheidungen beginnen mit besseren Daten.', intro:'Wir entwickeln Reporting-, Dashboard- und Automatisierungslösungen für Unternehmen, die schneller verstehen wollen, was in ihrem Geschäft passiert.',
    problem:'Ihre Daten sind da. Nur die Antworten fehlen.', problemText:'Zahlen liegen verstreut in Excel-Dateien und Systemen, kommen zu spät und verursachen zu viel manuelle Arbeit.',
    cards:[['Excel-Chaos','Widersprüchliche Dateien und Werte erschweren verlässliche Entscheidungen.',FileSpreadsheet],['Verspätete Zahlen','Berichte kommen, wenn der Zeitpunkt zum Handeln bereits vorbei ist.',RefreshCw],['Manuelle Arbeit','Kopieren, Formatieren und Verteilen kostet wertvolle Zeit.',Workflow],['Fehlender Überblick','Kein System zeigt eine verlässliche Gesamtsicht.',BarChart3]],
    solution:'Klarheit statt noch eines Tools.', solutionText:'Jede Lösung beginnt mit einer konkreten Geschäftsfrage. Technologie ist nur das Mittel, sie zu beantworten.',
    services:[['Management-Dashboards','Umsatz, Kosten, Pipeline und Budget in einer aktuellen Oberfläche.',LayoutDashboard],['Reporting-Automatisierung','Berichte erstellen, prüfen und verteilen sich automatisch.',Workflow],['Forecasting & Planung','Nachvollziehbare Szenarien und Frühwarnung bei Abweichungen.',LineChart],['Individuelle Datenlösungen','Schnittstellen und interne Tools passend zum Prozess.',ShieldCheck]],
    process:'Vom ersten Gespräch zum laufenden System.', steps:[['01','Erstgespräch','Wir klären Ziele, Systeme und die Entscheidungen, die unterstützt werden sollen.'],['02','Konzept','Sie erhalten einen klaren Umfang, technische Richtung und ein Angebot.'],['03','Umsetzung','Wir arbeiten in kurzen Etappen und zeigen früh nutzbare Ergebnisse.'],['04','Übergabe','Dokumentation, Einweisung und optionale Betreuung.']],
    why:'Business-Verständnis trifft Softwareentwicklung.', whyText:'Vantura verbindet Reporting-, Forecasting- und Investment-Erfahrung mit praktischer Softwareentwicklung. Das Ergebnis ist ein wartbares Entscheidungssystem, das im Alltag genutzt wird.',
    faq:'Häufige Fragen', faqs:[['Müssen wir unsere Systeme wechseln?','Nein. Wir binden bestehende Werkzeuge und Datenquellen an.'],['Wie schnell sehen wir Ergebnisse?','Eine erste nutzbare Version ist typischerweise nach zwei bis vier Wochen verfügbar.'],['Was kostet ein Projekt?','Nach einer kurzen Analyse erhalten Sie einen klaren Umfang und Festpreis.']],
    cta:'Machen Sie aus Daten bessere Entscheidungen.', ctaText:'Erzählen Sie uns, wo Reporting, Planung oder manuelle Prozesse Ihr Team ausbremsen.', projects:'Projekte', websites:'Websites', footer:'Reporting, Dashboards und Automatisierung für Unternehmen, die ihre Daten verstehen wollen.'
  }
} as const

export function LocalizedHome({locale}:{locale:'en'|'de'}){
 const t=text[locale], prefix=locale==='de'?'/de':''
 const contact=`mailto:jk@vantura-studios.com?subject=${encodeURIComponent(locale==='de'?'Erstgespräch: Reporting & Daten':'Intro call: Reporting & data')}`
 return <div className="min-h-screen bg-white text-ink"><LanguageRedirect locale={locale}/>
  <header className="sticky top-0 z-50 border-b border-line bg-white/90 backdrop-blur"><nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6 lg:px-8"><Link href={`${prefix}/`} className="text-[17px] font-semibold">Vantura</Link><div className="flex items-center gap-3"><LanguageSwitch locale={locale}/><a href={contact} className="hidden rounded-full bg-ink px-4 py-2 text-sm font-medium text-white sm:block">{t.call}</a></div></nav></header>
  <main><section className="bg-paper"><div className="mx-auto grid max-w-6xl gap-14 px-6 py-24 lg:grid-cols-2 lg:px-8 lg:py-32"><div><p className="inline-flex rounded-full border border-line bg-white px-3 py-1.5 text-sm text-muted">{t.badge}</p><h1 className="mt-7 text-5xl font-semibold tracking-[-.045em] sm:text-7xl">{t.hero}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted">{t.intro}</p><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.call}<ArrowRight size={16}/></a></div><HeroDashboard/></div></section>
  <section className="mx-auto max-w-6xl px-6 py-24 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.problem}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{t.problemText}</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{t.cards.map(([a,b,I])=><article key={a as string} className="rounded-2xl border border-line p-6"><I size={20}/><h3 className="mt-5 font-semibold">{a}</h3><p className="mt-2 text-sm leading-6 text-muted">{b}</p></article>)}</div></section>
  <section className="bg-paper py-24"><div className="mx-auto max-w-6xl px-6 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.solution}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{t.solutionText}</p><div className="mt-12 grid gap-6 md:grid-cols-2">{t.services.map(([a,b,I])=><article key={a as string} className="rounded-2xl border border-line bg-white p-8"><I size={22}/><h3 className="mt-5 text-xl font-semibold">{a}</h3><p className="mt-3 leading-7 text-muted">{b}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-6 py-24 lg:px-8"><ShowcaseDashboard/></section>
  <section className="bg-ink py-24 text-white"><div className="mx-auto max-w-6xl px-6 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.process}</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{t.steps.map(([n,a,b])=><article key={n} className="rounded-2xl border border-white/15 p-6"><p className="text-white/40">{n}</p><h3 className="mt-5 font-semibold">{a}</h3><p className="mt-3 text-sm leading-6 text-white/60">{b}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-6 py-24 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.why}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">{t.whyText}</p></section>
  <section className="bg-paper py-24"><div className="mx-auto max-w-4xl px-6"><h2 className="text-4xl font-semibold">{t.faq}</h2><div className="mt-10 divide-y divide-line border-y border-line">{t.faqs.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 leading-7 text-muted">{a}</p></details>)}</div></div></section>
  <section className="px-6 py-24 text-center"><h2 className="text-4xl font-semibold sm:text-6xl">{t.cta}</h2><p className="mx-auto mt-6 max-w-2xl text-lg text-muted">{t.ctaText}</p><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.call}<ArrowRight size={16}/></a></section></main>
  <footer className="border-t border-line"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 px-6 py-12 md:flex-row lg:px-8"><div><p className="font-semibold">Vantura</p><p className="mt-2 max-w-xs text-sm text-muted">{t.footer}</p></div><nav className="flex gap-6 text-sm text-muted"><Link href={`${prefix}/projekt/`}>{t.projects}</Link><Link href={`${prefix}/websites/`}>{t.websites}</Link></nav></div></footer>
 </div>
}
