import Link from 'next/link'
import { ArrowRight, Blocks, Bot, Code2, Gauge, Globe2, LayoutTemplate, LifeBuoy, Rocket, ShieldCheck, Smartphone, Workflow } from 'lucide-react'
import { LanguageRedirect } from './LanguageRedirect'
import { LanguageSwitch } from './LanguageSwitch'
import { ProjectDetails } from './ProjectDetails'

const project = {
 en:{title:'You have the idea. I build the project.',lead:'Apps, web apps, internal tools, automations and MVPs — from the first structure to a finished, usable product.',badge:'Product development with Vantura',nav:['Services','Process'],services:[['Apps & web apps','Responsive products for mobile and web, built for real usage.',Smartphone],['MVPs & prototypes','Turn an idea into a testable first version without months of preparation.',Blocks],['Automation','Workflows, integrations and AI processes that reduce manual work.',Workflow],['Internal tools','Dashboards, calculators and portals tailored to your operation.',Gauge],['Project rescue','Analyse, stabilise and finish incomplete or stalled projects.',LifeBuoy],['AI features','Integrate useful AI features, agents and local models into products.',Bot]],process:'Clear process. Early results.',steps:[['01','Understand','We clarify the goal, users and what the first useful version must do.'],['02','Plan & prototype','You receive a clear scope, user flow, technical direction and an early concept.'],['03','Design & build','I develop in short iterations and show working results early.'],['04','Launch & support','Deployment, setup, handover and optional ongoing support.']],cta:'Tell me what your project should do.',button:'Discuss your idea'},
 de:{title:'Du hast die Idee. Ich baue dein Projekt.',lead:'Apps, Web-Apps, interne Tools, Automationen und MVPs – von der ersten Struktur bis zum fertigen, nutzbaren Produkt.',badge:'Produktentwicklung mit Vantura',nav:['Leistungen','Prozess'],services:[['Apps & Web-Apps','Produkte für Mobile und Web – responsiv, schnell und auf echte Nutzung ausgelegt.',Smartphone],['MVPs & Prototypen','Eine Idee wird ohne monatelange Vorarbeit zu einer testbaren ersten Version.',Blocks],['Automationen','Abläufe, Schnittstellen und KI-Workflows reduzieren manuelle Arbeit.',Workflow],['Interne Tools','Dashboards, Kalkulatoren und Portale passend zum Prozess.',Gauge],['Projekt-Rettung','Halbfertige oder festgefahrene Projekte analysieren, stabilisieren und fertigstellen.',LifeBuoy],['KI-Features','Sinnvolle KI-Funktionen, Agenten und lokale Modelle integrieren.',Bot]],process:'Klarer Prozess. Frühe Ergebnisse.',steps:[['01','Verstehen','Wir klären Ziel, Nutzer und was die erste gute Version können muss.'],['02','Planen & prototypisieren','Du erhältst einen klaren Umfang, Nutzerfluss, technische Richtung und früh ein sichtbares Konzept.'],['03','Gestalten & bauen','Ich entwickle in kurzen Etappen und zeige früh nutzbare Ergebnisse.'],['04','Veröffentlichen & betreuen','Deployment, Einrichtung, Übergabe und auf Wunsch laufende Betreuung.']],cta:'Erzähl mir, was dein Projekt können soll.',button:'Idee besprechen'}
} as const

const websites = {
 en:{title:'Websites that do more than look good.',lead:'Modern websites for small businesses, hospitality and local service providers — clearly positioned, mobile-first and ready to generate enquiries.',badge:'Vantura Website Studio',nav:['Work','Offer'],services:[['Individual design','A distinct visual identity instead of generic template aesthetics.',LayoutTemplate],['Mobile first','Clean usability across smartphones, tablets and desktops.',Smartphone],['Clear conversion paths','Strong structure, understandable copy and focused calls to action.',Globe2],['Launch included','Technical setup, deployment, domain support and clean handover.',Rocket]],process:'The website sprint.',steps:[['01','Position','Clarify the offer, audience and primary action.'],['02','Design','Create structure, copy direction and a fitting visual system.'],['03','Build','Implement a fast, responsive and accessible website.'],['04','Launch','Publish, connect the domain and hand everything over.']],cta:'Your website can start small and still look professional.',button:'Discuss your website'},
 de:{title:'Websites, die nicht nur gut aussehen.',lead:'Moderne Websites für kleine Unternehmen, Gastronomie und lokale Dienstleister – klar positioniert, mobil optimiert und bereit für echte Anfragen.',badge:'Vantura Website Studio',nav:['Arbeiten','Angebot'],services:[['Individuelles Design','Ein eigener Auftritt statt austauschbarer Baukasten-Optik.',LayoutTemplate],['Mobile First','Saubere Nutzung auf Smartphone, Tablet und Desktop.',Smartphone],['Klare Wege zur Anfrage','Verständliche Texte, gute Struktur und starke Handlungsaufforderungen.',Globe2],['Launch inklusive','Technische Einrichtung, Veröffentlichung, Domain und Übergabe.',Rocket]],process:'Der Website-Sprint.',steps:[['01','Positionieren','Angebot, Zielgruppe und wichtigste Handlung klären.'],['02','Gestalten','Struktur, Text-Richtung und passendes Design entwickeln.'],['03','Bauen','Eine schnelle, responsive und zugängliche Website umsetzen.'],['04','Veröffentlichen','Domain verbinden, live stellen und sauber übergeben.']],cta:'Deine Website kann klein starten und trotzdem professionell wirken.',button:'Website besprechen'}
} as const

export function LocalizedServicePage({locale,type}:{locale:'en'|'de';type:'project'|'websites'}){
 const isProject=type==='project'
 const t=(isProject?project:websites)[locale]
 const prefix=locale==='de'?'/de':''
 const contact=`mailto:hello@vantura-studios.com?subject=${encodeURIComponent(isProject?(locale==='de'?'Projektanfrage':'Project enquiry'):(locale==='de'?'Website-Anfrage':'Website enquiry'))}`
 return <div className="min-h-screen bg-white text-ink"><LanguageRedirect locale={locale}/>
  <header className="border-b border-line bg-white/90 backdrop-blur"><nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6 lg:px-8"><Link href={`${prefix}/`} className="text-[17px] font-semibold">Vantura</Link><div className="flex items-center gap-3"><LanguageSwitch locale={locale}/><a href={contact} className="hidden rounded-full bg-ink px-4 py-2 text-sm font-medium text-white sm:block">{t.button}</a></div></nav></header>
  <main><section className="overflow-hidden border-b border-line bg-paper"><div className="mx-auto grid max-w-6xl gap-14 px-6 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-line bg-white px-3 py-1.5 text-xs font-semibold uppercase tracking-[.16em] text-muted">{isProject?<Code2 size={14}/>:<Globe2 size={14}/>} {t.badge}</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.05em] sm:text-7xl">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">{t.lead}</p><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.button}<ArrowRight size={17}/></a></div><div className="rounded-[30px] bg-ink p-8 text-white shadow-2xl"><p className="text-xs uppercase tracking-[.16em] text-white/50">Vantura Build System</p><div className="mt-8 space-y-3">{t.steps.slice(0,3).map(([n,a])=><div key={n} className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/50">{n}</p><p className="mt-1 font-semibold">{a}</p></div>)}</div></div></div></section>
  <section className="mx-auto max-w-6xl px-6 py-20 lg:px-8 lg:py-28"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{t.services.map(([a,b,I])=><article key={a as string} className="rounded-[26px] border border-line p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-paper"><I size={20}/></span><h2 className="mt-6 text-xl font-semibold">{a}</h2><p className="mt-3 leading-7 text-muted">{b}</p></article>)}</div></section>
  <section className="bg-ink py-20 text-white"><div className="mx-auto max-w-6xl px-6 lg:px-8"><h2 className="text-4xl font-semibold sm:text-5xl">{t.process}</h2><div className="mt-10 divide-y divide-white/10 border-y border-white/10">{t.steps.map(([n,a,b])=><div key={n} className="grid gap-3 py-6 sm:grid-cols-[56px_180px_1fr]"><p className="text-white/35">{n}</p><p className="font-semibold">{a}</p><p className="text-white/60">{b}</p></div>)}</div></div></section>
  {isProject&&<ProjectDetails locale={locale}/>}<section className="bg-paper px-6 py-24 text-center"><ShieldCheck className="mx-auto"/><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold sm:text-6xl">{t.cta}</h2><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white">{t.button}<ArrowRight size={17}/></a></section></main>
 </div>
}
