import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Blocks, Bot, Braces, Gauge, Layers3, LifeBuoy, Rocket, ShieldCheck, Smartphone, Workflow } from 'lucide-react'
import { LanguageRedirect } from './LanguageRedirect'
import { LanguageSwitch } from './LanguageSwitch'

const copy = {
  en: {
    badge:'Vantura Product Studio', title:'From rough idea to a product people can actually use.', lead:'Apps, internal tools, automations and AI-enabled products — scoped clearly, prototyped early and built around the real workflow.', primary:'Discuss your idea',
    introTitle:'Not just code. A product system.', introLead:'Good software starts with the operating reality: who uses it, what slows them down and which decisions the product must make easier.',
    capabilities:[['Apps & web apps','Responsive products for mobile and web with focused flows and a clean interaction model.',Smartphone],['MVPs & prototypes','A testable first version that proves the core experience before the scope grows.',Blocks],['Internal tools','Dashboards, calculators, portals and operational systems tailored to real processes.',Gauge],['Automation','Connected workflows and integrations that remove repetitive manual work.',Workflow],['AI features','Agents, local models and useful AI functions embedded where they create leverage.',Bot],['Project rescue','Analyse, stabilise and finish products that are incomplete, fragile or stuck.',LifeBuoy]],
    selectedTitle:'Products built around real operating problems.', selectedLead:'A mix of live products, internal systems and focused product experiments.',
    processTitle:'Move quickly without building blindly.', process:[['01','Frame','Define the problem, users, constraints and the smallest version worth building.'],['02','Prototype','Make the core flow visible and testable before heavy implementation.'],['03','Build','Develop in short cycles with working increments and clear technical decisions.'],['04','Launch','Deploy, document and create a stable handover or ongoing product rhythm.']],
    modesTitle:'Different projects need different levels of involvement.', modes:[['Product sprint','A focused prototype or MVP with a clearly limited scope.'],['Build partner','Continuous product development across several releases.'],['Rescue & stabilise','Technical and product review, fixes and completion of an existing project.'],['Internal system','A tailored tool for a specific operational process or team.']],
    cta:'Tell me what the product should make easier.'
  },
  de: {
    badge:'Vantura Product Studio', title:'Von der groben Idee zum Produkt, das wirklich genutzt wird.', lead:'Apps, interne Tools, Automationen und KI-gestützte Produkte – klar abgegrenzt, früh prototypisiert und rund um den echten Arbeitsablauf gebaut.', primary:'Idee besprechen',
    introTitle:'Nicht nur Code. Ein Produktsystem.', introLead:'Gute Software beginnt bei der operativen Realität: Wer nutzt sie, was kostet Zeit und welche Entscheidungen muss das Produkt leichter machen?',
    capabilities:[['Apps & Web-Apps','Responsive Produkte für Mobile und Web mit fokussierten Abläufen und einem klaren Interaktionsmodell.',Smartphone],['MVPs & Prototypen','Eine testbare erste Version, die das Kernerlebnis beweist, bevor der Umfang wächst.',Blocks],['Interne Tools','Dashboards, Kalkulatoren, Portale und operative Systeme passend zu echten Prozessen.',Gauge],['Automationen','Verbundene Workflows und Integrationen, die wiederkehrende manuelle Arbeit entfernen.',Workflow],['KI-Features','Agenten, lokale Modelle und sinnvolle KI-Funktionen dort, wo sie echten Hebel erzeugen.',Bot],['Projekt-Rettung','Produkte analysieren, stabilisieren und fertigstellen, die unfertig, fragil oder festgefahren sind.',LifeBuoy]],
    selectedTitle:'Produkte rund um echte operative Probleme.', selectedLead:'Live-Produkte, interne Systeme und fokussierte Produktexperimente.',
    processTitle:'Schnell vorankommen, ohne blind zu bauen.', process:[['01','Rahmen setzen','Problem, Nutzer, Grenzen und die kleinste sinnvolle Version definieren.'],['02','Prototypisieren','Den Kernablauf sichtbar und testbar machen, bevor tief implementiert wird.'],['03','Bauen','In kurzen Zyklen entwickeln – mit funktionierenden Zwischenständen und klaren technischen Entscheidungen.'],['04','Veröffentlichen','Deployen, dokumentieren und eine stabile Übergabe oder einen laufenden Produktrhythmus schaffen.']],
    modesTitle:'Unterschiedliche Projekte brauchen unterschiedliche Formen der Zusammenarbeit.', modes:[['Product Sprint','Ein fokussierter Prototyp oder MVP mit klar begrenztem Umfang.'],['Build Partner','Kontinuierliche Produktentwicklung über mehrere Releases.'],['Rescue & Stabilisierung','Technische und produktseitige Prüfung, Fixes und Abschluss eines bestehenden Projekts.'],['Internes System','Ein maßgeschneidertes Tool für einen konkreten operativen Prozess oder ein Team.']],
    cta:'Erzähl mir, was das Produkt leichter machen soll.'
  }
} as const

const projects = [
  {name:'Grace',kind:'AI workspace',status:'Live product',href:'https://meet-grace.com',gradient:'from-violet-700 via-fuchsia-600 to-blue-500',preview:'workspace'},
  {name:'Recruvia',kind:'Private recruitment platform',status:'Enterprise concept',href:'/recruvia/',gradient:'from-blue-700 via-cyan-600 to-emerald-400',preview:'dashboard'},
  {name:'HotCold',kind:'Mobile product',status:'In development',href:'',gradient:'from-rose-500 via-orange-400 to-amber-300',preview:'mobile'},
  {name:'Internal calculators',kind:'Operational systems',status:'Client work',href:'',gradient:'from-slate-800 via-blue-700 to-cyan-500',preview:'data'},
]

function ProductPreview({type}:{type:string}){
  if(type==='workspace') return <div className="grid h-full grid-cols-[110px_1fr] overflow-hidden rounded-[26px] border border-white/20 bg-slate-950/50 backdrop-blur"><div className="border-r border-white/10 p-4"><div className="h-8 w-8 rounded-xl bg-white/15"/><div className="mt-8 space-y-3">{[1,2,3,4].map(i=><div key={i} className="h-2 rounded-full bg-white/10"/>)}</div></div><div className="p-5"><div className="flex justify-between"><div className="h-3 w-28 rounded-full bg-white/20"/><div className="h-7 w-20 rounded-full bg-white/15"/></div><div className="mt-8 grid gap-3"><div className="w-[78%] rounded-2xl bg-white/12 p-4"><div className="h-2 w-3/4 rounded-full bg-white/25"/><div className="mt-3 h-2 w-1/2 rounded-full bg-white/15"/></div><div className="ml-auto w-[66%] rounded-2xl bg-violet-300/25 p-4"><div className="h-2 w-2/3 rounded-full bg-white/30"/></div></div></div></div>
  if(type==='dashboard') return <div className="h-full rounded-[26px] border border-white/25 bg-white/90 p-5 text-slate-900"><div className="flex justify-between"><div><div className="h-3 w-28 rounded-full bg-slate-200"/><div className="mt-2 h-2 w-20 rounded-full bg-slate-100"/></div><div className="h-7 w-24 rounded-full bg-emerald-100"/></div><div className="mt-6 grid grid-cols-3 gap-3">{[1,2,3].map(i=><div key={i} className="rounded-xl border border-slate-100 p-3"><div className="h-2 w-12 rounded bg-slate-200"/><div className="mt-3 h-6 w-14 rounded bg-slate-900"/></div>)}</div><div className="mt-4 space-y-2">{[1,2,3].map(i=><div key={i} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><div className="h-8 w-8 rounded-lg bg-blue-100"/><div className="h-2 flex-1 rounded bg-slate-100"/><div className="h-2 w-16 rounded bg-emerald-300"/></div>)}</div></div>
  if(type==='mobile') return <div className="flex h-full items-center justify-center gap-6"><div className="h-[88%] w-40 rounded-[34px] border-[7px] border-slate-950 bg-white p-3 shadow-2xl"><div className="mx-auto h-3 w-16 rounded-full bg-slate-950"/><div className="mt-8 h-20 rounded-2xl bg-gradient-to-br from-rose-300 to-orange-200"/><div className="mt-4 space-y-3">{[1,2,3].map(i=><div key={i} className="h-12 rounded-xl bg-slate-100"/>)}</div></div><div className="hidden h-[78%] w-36 rotate-6 rounded-[30px] border-[7px] border-slate-900 bg-slate-50 p-3 shadow-xl sm:block"><div className="mt-8 h-36 rounded-2xl bg-slate-900"/><div className="mt-4 h-10 rounded-xl bg-orange-200"/></div></div>
  return <div className="grid h-full grid-cols-6 items-end gap-3 rounded-[26px] border border-white/20 bg-slate-950/40 p-6 backdrop-blur">{[38,62,48,78,68,92].map((h,i)=><div key={i} className="rounded-t-xl bg-cyan-300/70" style={{height:`${h}%`}}/>)}</div>
}

export function LocalizedProjectsPage({locale}:{locale:'en'|'de'}){
  const t=copy[locale]; const prefix=locale==='de'?'/de':''; const contact=`mailto:jk@vantura-studios.com?subject=${encodeURIComponent(locale==='de'?'Projektanfrage':'Project enquiry')}`
  return <div className="min-h-screen bg-[#f6f8fb] text-ink"><LanguageRedirect locale={locale}/>
    <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-[#f6f8fb]/90 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6 lg:px-8"><Link href={`${prefix}/`} className="font-semibold tracking-[-.03em]">Vantura Studios</Link><div className="flex items-center gap-3"><LanguageSwitch locale={locale}/><a href={contact} className="hidden rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white sm:block">{t.primary}</a></div></nav></header>
    <main>
      <section className="relative overflow-hidden border-b border-slate-200"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_16%,rgba(59,130,246,.16),transparent_28%),radial-gradient(circle_at_15%_85%,rgba(124,58,237,.10),transparent_30%)]"/><div className="relative mx-auto grid min-h-[760px] max-w-7xl gap-14 px-6 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/80 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.16em] text-blue-700"><Braces size={14}/>{t.badge}</div><h1 className="mt-7 max-w-4xl text-5xl font-semibold leading-[.91] tracking-[-.065em] sm:text-7xl lg:text-[88px]">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">{t.lead}</p><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 text-sm font-semibold text-white">{t.primary}<ArrowRight size={17}/></a></div><div className="relative min-h-[610px]"><div className="absolute inset-x-0 top-7 h-[500px] rotate-[-2deg] rounded-[38px] bg-slate-950 p-7 text-white shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-white/40">Product build</p><p className="mt-2 text-2xl font-semibold">From system map to working product.</p></div><Rocket/></div><div className="mt-9 grid h-[360px] grid-cols-[120px_1fr] overflow-hidden rounded-[28px] border border-white/10 bg-white/5"><div className="border-r border-white/10 p-4"><div className="h-9 w-9 rounded-xl bg-blue-500"/><div className="mt-9 space-y-4">{[1,2,3,4,5].map(i=><div key={i} className="h-2 rounded-full bg-white/10"/>)}</div></div><div className="p-6"><div className="flex items-center justify-between"><div className="h-3 w-32 rounded-full bg-white/20"/><div className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs text-emerald-300">Build healthy</div></div><div className="mt-8 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-white/8 p-5"><Layers3/><p className="mt-16 text-xl font-semibold">Product<br/>architecture</p></div><div className="rounded-2xl bg-blue-500 p-5"><ShieldCheck/><p className="mt-16 text-xl font-semibold">Stable<br/>delivery</p></div></div></div></div></div><div className="absolute bottom-0 right-8 rounded-[28px] bg-white p-6 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[.16em] text-black/35">Working rhythm</p><div className="mt-5 flex gap-3">{['Scope','Prototype','Build','Launch'].map((s,i)=><div key={s} className={`rounded-full px-4 py-2 text-xs font-semibold ${i===2?'bg-blue-600 text-white':'bg-slate-100'}`}>{s}</div>)}</div></div></div></div></section>
      <section className="bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><p className="pt-3 text-xs font-semibold uppercase tracking-[.2em] text-blue-600">Product thinking</p><div><h2 className="text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">{t.introTitle}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">{t.introLead}</p></div></div><div className="mt-16 divide-y divide-slate-200 border-y border-slate-200">{t.capabilities.map(([title,description,Icon],index)=><article key={title} className="grid gap-5 py-7 md:grid-cols-[70px_1fr_1.2fr_auto] md:items-center"><span className="text-xs font-semibold text-black/35">0{index+1}</span><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100"><Icon size={19}/></span><h3 className="text-xl font-semibold">{title}</h3></div><p className="leading-7 text-muted">{description}</p><ArrowUpRight className="hidden text-black/30 md:block"/></article>)}</div></div></section>
      <section className="bg-slate-950 py-24 text-white lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-300">Selected products</p><h2 className="mt-5 text-4xl font-semibold leading-[.95] tracking-[-.055em] sm:text-6xl">{t.selectedTitle}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-white/55">{t.selectedLead}</p></div><div className="mt-14 grid gap-6 lg:grid-cols-2">{projects.map((item,index)=>{const card=<article className="overflow-hidden rounded-[34px] border border-white/10 bg-white/5"><div className={`h-[430px] bg-gradient-to-br ${item.gradient} p-6`}><ProductPreview type={item.preview}/></div><div className="flex items-end justify-between gap-6 p-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-white/40">{item.status}</p><h3 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{item.name}</h3><p className="mt-2 text-white/55">{item.kind}</p></div>{item.href&&<ArrowUpRight/>}</div></article>;return item.href?<Link key={item.name} href={item.href} className="group">{card}</Link>:<div key={item.name}>{card}</div>})}</div></div></section>
      <section className="py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-600">Delivery</p><h2 className="mt-5 text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">{t.processTitle}</h2></div><div className="divide-y divide-slate-200 border-y border-slate-200">{t.process.map(([n,title,description])=><div key={n} className="grid gap-3 py-7 sm:grid-cols-[60px_180px_1fr]"><p className="text-black/35">{n}</p><p className="font-semibold">{title}</p><p className="text-muted">{description}</p></div>)}</div></div></section>
      <section className="bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><h2 className="max-w-4xl text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">{t.modesTitle}</h2><div className="mt-12 grid gap-5 md:grid-cols-2">{t.modes.map(([title,description],index)=><article key={title} className="rounded-[30px] border border-slate-200 bg-[#f6f8fb] p-8"><span className="text-xs font-semibold text-black/35">0{index+1}</span><h3 className="mt-16 text-2xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-4 max-w-xl leading-7 text-muted">{description}</p></article>)}</div></div></section>
      <section className="bg-gradient-to-br from-blue-700 via-indigo-700 to-violet-700 px-6 py-28 text-center text-white"><h2 className="mx-auto max-w-4xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">{t.cta}</h2><a href={contact} className="mt-9 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-slate-950">{t.primary}<ArrowRight size={17}/></a></section>
    </main></div>
}