export const AE = {
  name: 'Arboretum Ellerhoop',
  claim: 'Der schönste Garten im Norden',
  description:
    'Norddeutsche Gartenschau auf 17,3 Hektar in Ellerhoop-Thiensen: Themengärten, Deutschlands größte Strauch-Pfingstrosen-Sammlung, Lotosblüte, Bauerngarten und Café im Münsterhof.',
  url: 'https://vantura-studios.com/arboretum',
  address: 'Thiensen 4',
  zip: '25373 Ellerhoop',
  phone: '04120 218',
  phoneHref: 'tel:+494120218',
  email: 'info@arboretum-ellerhoop.de',
  vereinEmail: 'verein@arboretum-ellerhoop.de',
  instagram: 'https://www.instagram.com/arboretum_ellerhoop/',
  facebook: 'https://www.facebook.com/arboretumellerhoop',
  shop: 'https://pretix.eu/arboretum-ellerhoop/va/',
  gaertnerei: 'https://gaertnerei-am-arboretum.de/',
  hvv: 'https://www.hvv.de/de',
  parkplan: 'https://www.arboretum-ellerhoop.de/wp-content/uploads/2024/06/2023_Parkplan_A4_ll.pdf',
  baumkataster: 'https://www.arboretum-ellerhoop.de/wp-content/uploads/2023/09/2023-Baumbestandsliste-Arboretum-Ellerhoop.pdf',
  baumbestandsplan: 'https://www.arboretum-ellerhoop.de/wp-content/uploads/2025/05/Baumbestandsplan.pdf',
  mitgliedschaft: 'https://www.arboretum-ellerhoop.de/wp-content/uploads/2024/07/2024_04_Aufnahmeantrag-SEPA-Lastschriftmandat.pdf',
  iban: 'DE42 2305 1030 0006 1088 80',
  bic: 'NOLADE21SHO',
  bank: 'Sparkasse Südholstein',
  register: 'VR 895 · Amtsgericht Elmshorn',
  vat: 'DE338531042',
} as const

export const hours = [
  { when: '15. Januar – Ende Februar', garden: '10–16 Uhr', cafe: 'nach Wetter, siehe Aktuelles' },
  { when: '1. März – 14. März', garden: '10–17 Uhr', cafe: 'unter der Woche ab 11 Uhr, Wochenende ab 10 Uhr' },
  { when: '15. März bis Sommerzeit', garden: '10–18 Uhr', cafe: 'schließt 1 Stunde vor dem Park' },
  { when: 'Hauptsaison (Sommerzeit)', garden: '10–19 Uhr', cafe: 'schließt 1 Stunde vor dem Park' },
  { when: '15. September – 14. Oktober', garden: '10–18 Uhr', cafe: 'schließt 1 Stunde vor dem Park' },
  { when: '15. Oktober bis Winterzeit', garden: '10–17 Uhr', cafe: 'schließt 1 Stunde vor dem Park' },
  { when: 'Winterzeit bis 30. November', garden: '10–16 Uhr', cafe: 'schließt 1 Stunde vor dem Park' },
  { when: '1. Dezember – 14. Januar', garden: 'Betriebsruhe', cafe: 'geschlossen' },
]

export const prices = [
  { label: 'Erwachsene', value: '10,00 €' },
  { label: 'Ermäßigt', value: '8,00 €', note: 'Schüler:innen, Student:innen, Auszubildende, Menschen mit Schwerbehinderung, Grundsicherung, Ehrenamtskarte SH. Merkzeichen B: Begleitperson frei.' },
  { label: 'Kinder bis 16 Jahre', value: 'frei' },
  { label: 'Gruppen ab 12 Personen', value: '8,00 € / Person' },
  { label: 'Abendticket ab 17 Uhr', value: '6,00 €', note: 'Nur Beginn der Sommerzeit bis 15. September. Nicht an Veranstaltungstagen.' },
  { label: 'Mitglieder', value: '5,00 €' },
  { label: 'Dauerkarte', value: '80,00 €', note: 'Ein Jahr ab Ausstellung. Partner-Dauerkarte 65,00 € bei gleichzeitigem Erwerb. Mitglieder 50,00 €.' },
  { label: 'Veranstaltungen', value: '10,00 €', note: 'Kein Gruppentarif, kein Abendticket.' },
]

export const bloom = [
  { name: 'Frühblüher', when: 'ab März' },
  { name: 'Kamelien', when: 'ab März' },
  { name: 'Magnolien', when: 'Mitte April' },
  { name: 'Stiefmütterchen', when: 'Ende April' },
  { name: 'Narzissenwiese', when: 'Ende April / Anfang Mai' },
  { name: 'Rhododendron', when: 'Ende April / Anfang Mai' },
  { name: 'Glyzinien', when: 'Mai / Juni' },
  { name: 'Iris', when: 'Mitte Mai / Juni' },
  { name: 'Päonien', when: 'Mitte Mai / Juni' },
  { name: 'Rosen', when: 'Juni' },
  { name: 'Sommerblumen', when: 'Ende Juni' },
  { name: 'Seerosen', when: 'Juli' },
  { name: 'Lotos', when: 'Juli / August' },
  { name: 'Indian Summer', when: 'Mitte Oktober' },
]

export const events = [
  { date: '22. & 23. August 2026', title: 'Lotosblütenfest', text: 'Konzerte auf der Seebühne, Führungen, Markt, Kinderprogramm und Café – 10 bis 19 Uhr.', href: '/arboretum/lotosbluetenfest/' },
  { date: '5. September 2026, ab 6 Uhr', title: 'Früher Foto-Morgen', text: 'Das Arboretum im ersten Licht – für alle, die den Park still und fotografisch erleben möchten.' },
  { date: '27. September 2026, 11 Uhr', title: 'Sonntagsspaziergang', text: 'Mit Rainer Kumetat zu Stauden und Gräsern im goldenen Septemberlicht. Für Mitglieder kostenlos.' },
  { date: '11. Oktober 2026, 11–14 Uhr', title: 'Tradition des Räucherns', text: 'Workshop mit Kräuterfrau Renate Holtmeyer.' },
  { date: '23. Oktober 2026, bis 21 Uhr', title: 'Illumination', text: 'Stimmungsvoll beleuchtete Bäume – ohne Begleitprogramm.' },
  { date: '24. & 25. Oktober 2026, bis 20 Uhr', title: 'Herbstfest', text: 'Illuminierte Bäume und herbstliches Ambiente im ganzen Park.' },
  { date: '13. Dezember 2026', title: 'Winterfest', text: 'Auf dem Münsterhof – wenn der Park sonst in der Betriebsruhe liegt.' },
]

export const board = [
  ['1. Vorsitzende', 'Aenne von Wurmb'],
  ['2. Vorsitzender', 'Hanns-Jürgen Redeker'],
  ['Schriftführerin', 'Matina Buttjes'],
  ['Schatzmeisterin', 'Ann-Kathrin Tech'],
  ['Beisitzerin', 'Dr. Susanne Dohrn'],
  ['Beisitzer', 'Heiko Jessen'],
  ['Beisitzerin', 'Karin Wiedemann'],
]

export const exhibitors = [
  'Abel & Zimmer Wildfruchtspezialitäten',
  'Bäumchen näht',
  'Beate und Jens Kremkow – Steine und Mineralien',
  'Carmen & Andreas Hinz – Kunsthandwerk aus Gips und Holz',
  'Der Herzenmacher',
  'Der Stockmacher',
  'Dorothea Ginolas – Illustrationen',
  'Flair Provençal',
  'Glas-Feuerwerke',
  'Handmade 3 mal good',
  'HeideCuisine',
  'Imkerei Tietjen',
  'Jernej Licht & Design',
  'Katharina Brandt & Christiane Noetzel',
  'Kirsten Kasdorf – rund ums Schaf',
  'KWR-Handelsgesellschaft',
  'Liese Loges – Schmuck',
  'Lieblingsdinge von Tina',
  'Margit Wilkens – Tillandsien',
  'Metallgestaltung Liebert',
  'Ringana',
  'Rudi Hoffmann – Raps-Wärmekissen',
  'Staudengärtnerei Heiko Müller',
  'Suscha Vogel-Lobeck & Hugo Lobeck',
  'Suses Waschküche',
  'Volker Tonder – Forstmöbel',
  'Weingut Erik Sommer',
  'Zur Honigbiene',
]
